<?php

namespace Container55JfU4H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMessageHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Message\SendMessageHandler' shared autowired service.
     *
     * @return \App\Message\SendMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Message/SendMessageHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Message\\SendMessageHandler'])) {
            return $container->privates['App\\Message\\SendMessageHandler'];
        }

        return $container->privates['App\\Message\\SendMessageHandler'] = new \App\Message\SendMessageHandler($a);
    }
}
