<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFMChOQ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFMChOQ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQFMChOQ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQFMChOQ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQFMChOQ\App_KernelTestDebugContainer([
    'container.build_hash' => 'QFMChOQ',
    'container.build_id' => '8edef2ab',
    'container.build_time' => 1731595212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFMChOQ');
